using TMPro;
using UnityEngine;

public enum NpcType //NPC 종족
{
    elf,
    dwarf,
    human,
    guide
}

public class NpcInfo : MonoBehaviour
{
    [SerializeField] private NpcType type;

    NpcTalkData npcTalkData;
    UIManager uimanager;

    public TextMeshProUGUI NpcName;
    public TextMeshProUGUI NpcTalk;

    public string Name; // NPC이름은 직접 입력

    bool guideTalking = false;

    int i = 0;

    private void Start()
    {
      //  npcTalkData = FindAnyObjectByType<NpcTalkData>();
        uimanager = FindAnyObjectByType<UIManager>();
    }

    //public void printText()
    //{
    //    int selet = Random.Range(0, 5); 
    //    switch (type)
    //    {
    //        case NpcType.elf:
    //            NpcTalk.text = npcTalkData.elflist[selet];
    //            break;
    //        case NpcType.dwarf:
    //            NpcTalk.text = npcTalkData.dwarflist[selet];
    //            break;
    //        case NpcType.human:
    //            NpcTalk.text = npcTalkData.humanlist[selet];
    //            break;
    //        case NpcType.guide:
    //            guideTalking = true;
    //            i = 0;
    //            break;
    //    }
    //}

    //private void Update()
    //{
    //    if (guideTalking)
    //    {
    //        NpcTalk.text = npcTalkData.guidelist[i];
    //        if (Input.GetKeyDown(KeyCode.Space) && i < 4)
    //        {
    //            NpcTalk.text = npcTalkData.guidelist[i];
    //            if (i < 3) i += 1;
    //        }
    //    }
    //}

    private void OnCollisionEnter2D(Collision2D collision)
    {
        if (collision.gameObject.tag == "Player") // 충돌 이벤트를 통해 플레이어와 닿으면 작동
        {
            //printText();
            //if (npcTalkData == null)
            //    NpcName.text = Name;
            //uimanager.SetOnNPCTalkUI(); // 대화 UI 켜기
        }
    }

    private void OnCollisionExit2D(Collision2D collision) // 충돌에서 벗어나면 UI종료
    {
       // uimanager.SetOffNPCTalkUI(); // 대화 UI 끄기
        if (guideTalking == true) guideTalking = false;
    }

    private class NpcTalkData
    {
    }
}